dancing-karaoke/Dance-Dance-Pose

client/app.js
client/components/PlaySong.js
client/components/Sing.js
client/components/navbar.js
client/routes.js
package-lock.json
package.json

(feature)add singing pitch

---

client/components/Main.js
client/components/Sing.js

Adding karoake text

---

client/components/Sing.js

Karoake pointer

---

client/components/Main.js
client/components/Sing.js
client/components/webcam.js

merged sing and webcam components

---

client/components/webcam.js

got rid of recursion and can now adjust the bubble speed

---

client/components/Main.js
client/store/bubble.js
client/store/index.js
client/store/song.js
webpack.config.js

added songs to store

---

client/components/Sing.js

score adds in 1000s and time doesnt skip

---

client/components/main/Sing.js

Jimmy's-lyrics

---

public/style.css

fixed css file error

---

client/components/home/home-page.js
public/style.css

changed logo to homeLogo due to css conflict

---

client/components/menu/song-menu.js

added abba animation to song selection page

added abba animation to song selection page

---

client/components/home/home-page.js
client/components/main/Sing.js

Unmounting components

---

client/components/main/utils.js
client/components/main/webcam.js
client/components/menu/selected-song-menu.js
client/components/menu/song-menu.js
client/store/song.js
public/style.css

selecct-song-level

---

client/components/main/Main.js
client/components/main/webcam.js

play-button

---

client/components/bubbles/Fire.js
client/components/main/Sing.js
client/components/main/score.js
client/components/main/webcam.js
client/store/bubble.js
client/store/song.js
public/style.css

combined scores

---

client/components/main/utils.js
script/seed.js
server/api/index.js
server/api/songs.js
server/db/models/index.js
server/db/models/song.js

added to the backend but we can't connect it yet

---

client/components/main/webcam.js

webcam-no-bugs

---

client/components/main/utils.js
client/components/main/webcam.js

fixed bugs

---

client/components/main/webcam.js

loading-page

---

client/components/main/Sing.js

fixed destructuring bug and edited subtitles

---

client/components/main/webcam.js
package-lock.json

second-bubble

---

client/components/main/webcam.js
client/components/menu/selected-song-menu.js
client/components/menu/song-menu.js
public/style.css

cleaned song selection

---

beats.js
client/components/main/SongSelect.js
client/components/main/utils.js
client/components/main/webcam.js

with-gaga-beats

---

client/components/main/SongSelect.js
public/style.css

with-few-changes-in-style

---

client/components/main/Instructions.js
client/components/main/SongSelect.js
public/style.css
script/seed.js

put in the instructions and added a back button to the song screen

---

client/components/main/Sing.js
client/components/main/SongSelect.js
client/components/menu/end-menu.js
public/style.css

made the back button disappear on song menu when modal pops up

---

client/components/main/score.js
client/components/menu/end-menu.js
public/style.css
server/api/index.js

Score multiplier

---

client/components/main/Sing.js
client/components/menu/end-menu.js

fixed song time end and score threshhold

---

client/components/main/Instructions.js
client/components/menu/end-menu.js
public/style.css
script/seed.js
server/db/models/leaderboard.js

Leaderboard restrictions

---

public/style.css

fixed albums over modal

---

client/components/main/Sing.js
client/components/menu/end-menu.js
public/style.css

fix css styling

---

client/components/menu/song-menu.js

add back button to song select

---

client/components/menu/song-menu.js
public/style.css

fix z-index for back button and album select

---

server/api/users.spec.js

xit users test

---

README.md

Still need GIFS to show gameplay features
---

updated the README fully for text

---

README.md

added gifs to readme

---

README.md

small edits to README
